"""Clean IoC's public API."""

from .arguments import INJECT, REMOVE, ParameterContext, build_arg, derive, generic_arg, inject, select
from .components import (
    Component,
    ComponentActivation,
    ComponentBuilder,
    ComponentFilter,
    ComponentKind,
    Lifespan,
    all_components,
    default_component_filter,
)
from .container import (
    BuilderAlreadyBuiltError,
    CannotResolveError,
    Container,
    ContainerBuilder,
    ContainerBuildError,
    ResolutionContext,
    Scope,
    ScopeBuilder,
    ScopeProvisionError,
    UndeclaredScopeSlotError,
)
from .metadata import Tag
from .tooling import (
    BuildIssue,
    BuildReport,
    CompiledGraph,
    GraphChange,
    GraphDiff,
    GraphManifest,
    GraphRoot,
    GraphVisit,
    IssueSeverity,
    TypeAst,
    ValidationContext,
    ValidationRule,
)

__all__ = [
    "INJECT",
    "REMOVE",
    "BuilderAlreadyBuiltError",
    "CannotResolveError",
    "Component",
    "ComponentActivation",
    "ComponentBuilder",
    "ComponentFilter",
    "ComponentKind",
    "Container",
    "ContainerBuildError",
    "ContainerBuilder",
    "BuildIssue",
    "BuildReport",
    "CompiledGraph",
    "Lifespan",
    "GraphChange",
    "GraphDiff",
    "GraphManifest",
    "GraphRoot",
    "GraphVisit",
    "IssueSeverity",
    "ParameterContext",
    "ResolutionContext",
    "Scope",
    "ScopeBuilder",
    "ScopeProvisionError",
    "Tag",
    "TypeAst",
    "UndeclaredScopeSlotError",
    "ValidationContext",
    "ValidationRule",
    "all_components",
    "build_arg",
    "default_component_filter",
    "derive",
    "generic_arg",
    "inject",
    "select",
]
