"""Clean IoC's public API."""

from .arguments import INJECT, REMOVE, ParameterContext, build_arg, derive, generic_arg, inject, select
from .assemblies import Assembly, Expose, Use
from .components import (
    Component,
    ComponentActivation,
    ComponentBuilder,
    ComponentFilter,
    ComponentKind,
    Lifespan,
    RuntimeOwnerKind,
    all_components,
    default_component_filter,
)
from .container import (
    BuilderAlreadyBuiltError,
    CannotResolveError,
    Container,
    ContainerBuilder,
    ContainerBuildError,
    ProviderScopeClosedError,
    ResolutionContext,
    Scope,
    ScopeBuilder,
    ScopeClosedError,
    ScopeProvisionError,
    UndeclaredScopeSlotError,
)
from .metadata import Tag
from .providers import AsyncProvider, Provider
from .tooling import (
    BuildIssue,
    BuildReport,
    CandidateDecision,
    CompilationExplanation,
    CompiledGraph,
    DecisionOutcome,
    DefinitionOrigin,
    GraphChange,
    GraphDiff,
    GraphManifest,
    GraphRoot,
    GraphVisit,
    IssueSeverity,
    OwnershipRecord,
    OwnershipReport,
    SourceLocation,
    TypeAst,
    ValidationContext,
    ValidationRule,
)

__all__ = [
    "INJECT",
    "REMOVE",
    "BuilderAlreadyBuiltError",
    "Assembly",
    "CannotResolveError",
    "Component",
    "ComponentActivation",
    "ComponentBuilder",
    "ComponentFilter",
    "ComponentKind",
    "Container",
    "ContainerBuildError",
    "ContainerBuilder",
    "BuildIssue",
    "BuildReport",
    "AsyncProvider",
    "CandidateDecision",
    "CompilationExplanation",
    "CompiledGraph",
    "DecisionOutcome",
    "Expose",
    "DefinitionOrigin",
    "Lifespan",
    "RuntimeOwnerKind",
    "GraphChange",
    "GraphDiff",
    "GraphManifest",
    "GraphRoot",
    "GraphVisit",
    "IssueSeverity",
    "OwnershipRecord",
    "OwnershipReport",
    "ParameterContext",
    "Provider",
    "ProviderScopeClosedError",
    "ResolutionContext",
    "Scope",
    "ScopeBuilder",
    "ScopeClosedError",
    "ScopeProvisionError",
    "SourceLocation",
    "Tag",
    "TypeAst",
    "UndeclaredScopeSlotError",
    "Use",
    "ValidationContext",
    "ValidationRule",
    "all_components",
    "build_arg",
    "default_component_filter",
    "derive",
    "generic_arg",
    "inject",
    "select",
]
