name: Deploy MkDocs to GitHub Pages

on:
  workflow_dispatch:

permissions:
  contents: write # Grants write access to the repository

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install Uv
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Install dependencies with Poetry
        run: |
          make install-dev-deps

      - run: uv run mkdocs gh-deploy --force
