name: Publish Docs to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "docs/**"
      - "mkdocs.yml"

permissions:
  id-token: write # This is required for actions/deploy-pages
  contents: read # This is required for actions/checkout
  pages: write # This is required for actions/deploy-pages
jobs:
  publish-to-github-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set up uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies with uv
        run: |
          uv sync --group dev

      - name: Build docs site
        run: uv run mkdocs build

      - name: Upload site to artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload site folder
          path: "./site"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
