name: Release

on:
  workflow_dispatch
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2.4.0

      - name: Verify main branch
        run: |
          if [[ "$(git branch --show-current)" != "main" ]]; then
            echo "This workflow is only allowed on the main branch.";
            exit 1;
          fi

      - name: Set up Python
        uses: actions/setup-python@v4.6.0
        with:
          python-version: "3.10"

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Publish package on PyPI
        run: poetry publish --build -u __token__ -p ${{ secrets.PYPI_TOKEN }}
