name: Release

on:
  workflow_dispatch
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3.6.0
        with:
          fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@v4.6.0
        with:
          python-version: "3.10"

      - name: Upgrade pip
        run: |
          pip install --constraint=.github/workflows/constraints.txt pip
          pip --version

      - name: Install Poetry
        run: |
          pip install --constraint=.github/workflows/constraints.txt poetry
          poetry --version

      - name: Check if there is a parent commit
        id: check-parent-commit
        run: |
          echo "::set-output name=sha::$(git rev-parse --verify --quiet HEAD^)"

      - name: Build package
        run: |
          poetry build --ansi

      - name: Publish package on PyPI
        run: poetry publish --build -u __token__ -p ${{ secrets.PYPI_TOKEN }}
